name: Verify Build

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure CMake
        # Vi säger: Källkoden finns i Server, lägg build-filer i Server/build-ci
        run: cmake -S Server -B Server/build-ci

      - name: Build Server
        # Vi bygger mappen vi just skapade
        run: cmake --build Server/build-ci --config Release
